#!/bin/bash
read -d '' help <<-EOF

Generate Table Utility, by Tomer Godinger, October 2013
Creates a file containing a table which lists symbol names, addresses and
sizes for all symbols matching the given regular expression.

Usage: generateTable [OPTION] -r REGEX

Options:
  -h, -?           Print this information
  -r REGEX         The regular expression to match
  -v VMLINUX_FILE  The vmlinux.o file to analyze
  -s SYSTEM_MAP    The System.map file to analyze
  -o OUTPUT_FILE   Write the output to this file
  -k KERNEL_DIR    Directory in which to search for the required files
                   (should be a built Android kernel)
  -p               Keep intermediary files
  
Report bugs to whomever is in charge nowadays.
EOF

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Default option values
vmlinux_file="vmlinux.o"
system_map_file="System.map"
output_file="KernelTable"
kernel_dir="."

# Parse command line arguments
while getopts "h?r:v:s:o:k:p" opt; do
    case "$opt" in
    h|\?)
        echo "$help"
        exit 0
        ;;
    r)  regex=$OPTARG
        ;;
    v)  vmlinux_file=$OPTARG
        ;;
    s)  system_map_file=$OPTARG
        ;;
    o)  output_file=$OPTARG
        ;;
    k)  kernel_dir=$OPTARG
        ;;
    p)  keep_intermediaries=1
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

if [ "$regex" == "" ];
then
  echo "$help"
  exit 0
fi

# Create a file containing all the relevant offsets
grep "$regex" $kernel_dir/$system_map_file > .mapOffsets

# Create a file containing all the relevant sizes
nm --print-size --numeric-sort --radix=d $kernel_dir/$vmlinux_file | grep "$regex" > .mapSizes

# Join the two files on the symbol name
join -1 3 -2 4 -o 1.3,1.1,2.2 .mapOffsets .mapSizes > $output_file

# Remove intermediary files, unless specifically asked not to
if [ ! $keep_intermediaries ]
then
  rm .mapOffsets
  rm .mapSizes
fi
