# Automatically generated by configure - do not modify
TARGET_DIR=objs
TARGET_CONFIG_MAKE=config.make
TARGET_CFLAGS=-I$(SRC_PATH)/android/config/target-$(TARGET_ARCH)
SRC_PATH=/home/user/Desktop/qemu_new/DroidScope/qemu
